name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_ENV: test
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: nephslair_test
      DB_DIALECT: mysql
      JWT_SECRET: test_jwt_secret_key_for_ci
      PORT: 0

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nephslair_test
        # Service container içinde çalışan healthcheck (container içinden localhost'a ping)
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Create test environment file
        working-directory: ./backend
        run: |
          cat > .env.test << EOF
          NODE_ENV=${NODE_ENV}
          PORT=${PORT}
          DB_HOST=${DB_HOST}
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_NAME=${DB_NAME}
          DB_DIALECT=${DB_DIALECT}
          JWT_SECRET=${JWT_SECRET}
          JWT_EXPIRE=7d
          EOF

      - name: Install MySQL client & wait for service
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends mysql-client
          echo "Waiting for MySQL (service: mysql) to be ready..."
          for i in {1..90}; do
            if mysqladmin ping -h mysql -u root -proot --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... ($i/90)"
            sleep 1
          done
          # If still not healthy, fail fast
          if ! mysqladmin ping -h mysql -u root -proot --silent; then
            echo "❌ MySQL did not become ready in time."
            exit 1
          fi

      - name: Verify MySQL connection
        run: |
          mysql -h mysql -u root -proot -e "SELECT 1;" || exit 1
          echo "MySQL connection verified!"

      - name: Run migrations
        working-directory: ./backend
        run: |
          echo "Running migrations..."
          npx sequelize-cli db:migrate \
            --config config/config.js \
            --migrations-path migrations \
            --env test || {
              echo "❌ Migration failed!"
              echo "Cannot proceed with tests without database tables."
              exit 1
            }
          echo "✅ Migrations completed successfully!"

      - name: Verify database setup
        run: |
          echo "Verifying database tables..."
          TABLES=$(mysql -h mysql -u root -proot "$DB_NAME" -e "SHOW TABLES;" 2>&1)
          if [ $? -eq 0 ]; then
            echo "✅ Database tables exist:"
            echo "$TABLES"
          else
            echo "❌ Failed to verify database tables!"
            exit 1
          fi

      - name: Run tests
        working-directory: ./backend
        timeout-minutes: 10
        run: |
          echo "=========================================="
          echo "Starting Tests"
          echo "=========================================="
          echo "Environment: NODE_ENV=$NODE_ENV"
          echo "Database: $DB_NAME on $DB_HOST"
          echo "Database User: $DB_USER"
          echo "=========================================="
          echo ""
          echo "Verifying database connection before tests..."
          mysql -h mysql -u root -proot "$DB_NAME" -e "SELECT 1;" || {
            echo "❌ Cannot connect to database!"
            exit 1
          }
          echo "✅ Database connection OK"
          echo ""
          echo "Running Jest tests..."
          # Use --runInBand to run tests serially (important for DB connection pool)
          # Coverage is collected but won't fail the build if coverage is low
          if [ -x "./node_modules/.bin/jest" ]; then
            if ./node_modules/.bin/jest --runInBand --coverage --coverageReporters=text-summary; then
              TEST_EXIT_CODE=0
            else
              TEST_EXIT_CODE=$?
            fi
          else
            echo "⚠️ Jest binary not found, falling back to npm test (note: --runInBand may not apply)"
            if npm test; then
              TEST_EXIT_CODE=0
            else
              TEST_EXIT_CODE=$?
            fi
          fi
          if [ $TEST_EXIT_CODE -eq 0 ]; then
            echo ""
            echo "=========================================="
            echo "✅ All tests passed!"
            echo "=========================================="
          else
            echo ""
            echo "=========================================="
            echo "❌ Tests failed with exit code $TEST_EXIT_CODE"
            echo "=========================================="
            exit $TEST_EXIT_CODE
          fi

      - name: Upload coverage reports
        if: always()
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          file: ./backend/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
